"""added image attribute to posts

Revision ID: 2e52ea10611c
Revises: 226e2890fc0f
Create Date: 2026-02-27 11:06:17.074469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e52ea10611c'
down_revision: Union[str, Sequence[str], None] = '226e2890fc0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_url')
    # ### end Alembic commands ###
