"""add hashed_password

Revision ID: 335ae629c202
Revises: a56c3b53f92b
Create Date: 2026-02-26 14:15:33.925546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335ae629c202'
down_revision: Union[str, Sequence[str], None] = 'a56c3b53f92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add column as nullable
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))

    # Step 2: Fill existing rows with temporary value
    op.execute("UPDATE users SET hashed_password = 'temp_password'")

    # Step 3: Make column NOT NULL
    op.alter_column('users', 'hashed_password', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
